version: '3'

services:
  server:
    image: mei-ads-server:latest
    container_name: mei-ads-server-v1
    build:
      context: ./school
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - communication-tier
  app:
    image: mei-ads-app:latest
    container_name: mei-ads-app-v1
    build:
      context: ./MEI/mei-ads-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - communication-tier

networks:
  communication-tier:
    driver: bridge